// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package nexus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8cbf27b07a8ad20, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NetworkRequest struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkRequest) Reset()         { *m = NetworkRequest{} }
func (m *NetworkRequest) String() string { return proto.CompactTextString(m) }
func (*NetworkRequest) ProtoMessage()    {}
func (*NetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8cbf27b07a8ad20, []int{1}
}
func (m *NetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkRequest.Unmarshal(m, b)
}
func (m *NetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkRequest.Marshal(b, m, deterministic)
}
func (dst *NetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkRequest.Merge(dst, src)
}
func (m *NetworkRequest) XXX_Size() int {
	return xxx_messageInfo_NetworkRequest.Size(m)
}
func (m *NetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkRequest proto.InternalMessageInfo

func (m *NetworkRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type StartNetworkResponse struct {
	SwarmKey             string   `protobuf:"bytes,2,opt,name=swarm_key,json=swarmKey,proto3" json:"swarm_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartNetworkResponse) Reset()         { *m = StartNetworkResponse{} }
func (m *StartNetworkResponse) String() string { return proto.CompactTextString(m) }
func (*StartNetworkResponse) ProtoMessage()    {}
func (*StartNetworkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8cbf27b07a8ad20, []int{2}
}
func (m *StartNetworkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartNetworkResponse.Unmarshal(m, b)
}
func (m *StartNetworkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartNetworkResponse.Marshal(b, m, deterministic)
}
func (dst *StartNetworkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartNetworkResponse.Merge(dst, src)
}
func (m *StartNetworkResponse) XXX_Size() int {
	return xxx_messageInfo_StartNetworkResponse.Size(m)
}
func (m *StartNetworkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartNetworkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartNetworkResponse proto.InternalMessageInfo

func (m *StartNetworkResponse) GetSwarmKey() string {
	if m != nil {
		return m.SwarmKey
	}
	return ""
}

type NetworkStatusReponse struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Uptime               int64    `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	DiskUsage            int64    `protobuf:"varint,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkStatusReponse) Reset()         { *m = NetworkStatusReponse{} }
func (m *NetworkStatusReponse) String() string { return proto.CompactTextString(m) }
func (*NetworkStatusReponse) ProtoMessage()    {}
func (*NetworkStatusReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8cbf27b07a8ad20, []int{3}
}
func (m *NetworkStatusReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkStatusReponse.Unmarshal(m, b)
}
func (m *NetworkStatusReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkStatusReponse.Marshal(b, m, deterministic)
}
func (dst *NetworkStatusReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkStatusReponse.Merge(dst, src)
}
func (m *NetworkStatusReponse) XXX_Size() int {
	return xxx_messageInfo_NetworkStatusReponse.Size(m)
}
func (m *NetworkStatusReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkStatusReponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkStatusReponse proto.InternalMessageInfo

func (m *NetworkStatusReponse) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NetworkStatusReponse) GetUptime() int64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *NetworkStatusReponse) GetDiskUsage() int64 {
	if m != nil {
		return m.DiskUsage
	}
	return 0
}

type NetworkDiagnosticsResponse struct {
	NodeInfo             []byte   `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	Stats                []byte   `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkDiagnosticsResponse) Reset()         { *m = NetworkDiagnosticsResponse{} }
func (m *NetworkDiagnosticsResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkDiagnosticsResponse) ProtoMessage()    {}
func (*NetworkDiagnosticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8cbf27b07a8ad20, []int{4}
}
func (m *NetworkDiagnosticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkDiagnosticsResponse.Unmarshal(m, b)
}
func (m *NetworkDiagnosticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkDiagnosticsResponse.Marshal(b, m, deterministic)
}
func (dst *NetworkDiagnosticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkDiagnosticsResponse.Merge(dst, src)
}
func (m *NetworkDiagnosticsResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkDiagnosticsResponse.Size(m)
}
func (m *NetworkDiagnosticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkDiagnosticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkDiagnosticsResponse proto.InternalMessageInfo

func (m *NetworkDiagnosticsResponse) GetNodeInfo() []byte {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *NetworkDiagnosticsResponse) GetStats() []byte {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "nexus.Empty")
	proto.RegisterType((*NetworkRequest)(nil), "nexus.NetworkRequest")
	proto.RegisterType((*StartNetworkResponse)(nil), "nexus.StartNetworkResponse")
	proto.RegisterType((*NetworkStatusReponse)(nil), "nexus.NetworkStatusReponse")
	proto.RegisterType((*NetworkDiagnosticsResponse)(nil), "nexus.NetworkDiagnosticsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	StartNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*StartNetworkResponse, error)
	UpdateNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error)
	StopNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error)
	NetworkStats(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkStatusReponse, error)
	NetworkDiagnostics(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkDiagnosticsResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/nexus.Service/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) StartNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*StartNetworkResponse, error) {
	out := new(StartNetworkResponse)
	err := c.cc.Invoke(ctx, "/nexus.Service/StartNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpdateNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/nexus.Service/UpdateNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) StopNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/nexus.Service/StopNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) RemoveNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/nexus.Service/RemoveNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) NetworkStats(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkStatusReponse, error) {
	out := new(NetworkStatusReponse)
	err := c.cc.Invoke(ctx, "/nexus.Service/NetworkStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) NetworkDiagnostics(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkDiagnosticsResponse, error) {
	out := new(NetworkDiagnosticsResponse)
	err := c.cc.Invoke(ctx, "/nexus.Service/NetworkDiagnostics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	StartNetwork(context.Context, *NetworkRequest) (*StartNetworkResponse, error)
	UpdateNetwork(context.Context, *NetworkRequest) (*Empty, error)
	StopNetwork(context.Context, *NetworkRequest) (*Empty, error)
	RemoveNetwork(context.Context, *NetworkRequest) (*Empty, error)
	NetworkStats(context.Context, *NetworkRequest) (*NetworkStatusReponse, error)
	NetworkDiagnostics(context.Context, *NetworkRequest) (*NetworkDiagnosticsResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.Service/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_StartNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).StartNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.Service/StartNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).StartNetwork(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpdateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpdateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.Service/UpdateNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpdateNetwork(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_StopNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).StopNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.Service/StopNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).StopNetwork(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_RemoveNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).RemoveNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.Service/RemoveNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).RemoveNetwork(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_NetworkStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).NetworkStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.Service/NetworkStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).NetworkStats(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_NetworkDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).NetworkDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.Service/NetworkDiagnostics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).NetworkDiagnostics(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Service_Ping_Handler,
		},
		{
			MethodName: "StartNetwork",
			Handler:    _Service_StartNetwork_Handler,
		},
		{
			MethodName: "UpdateNetwork",
			Handler:    _Service_UpdateNetwork_Handler,
		},
		{
			MethodName: "StopNetwork",
			Handler:    _Service_StopNetwork_Handler,
		},
		{
			MethodName: "RemoveNetwork",
			Handler:    _Service_RemoveNetwork_Handler,
		},
		{
			MethodName: "NetworkStats",
			Handler:    _Service_NetworkStats_Handler,
		},
		{
			MethodName: "NetworkDiagnostics",
			Handler:    _Service_NetworkDiagnostics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_a8cbf27b07a8ad20) }

var fileDescriptor_service_a8cbf27b07a8ad20 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x8b, 0xc8, 0xbf, 0xb1, 0x78, 0xd8, 0xa0, 0x69, 0x20, 0x26, 0xba, 0xf1, 0x60, 0x3c,
	0x70, 0x10, 0xc3, 0x27, 0xc0, 0x83, 0x31, 0x51, 0xd2, 0x86, 0x33, 0xa9, 0x30, 0x34, 0x1b, 0xd2,
	0xdd, 0xda, 0x99, 0x82, 0x7c, 0x2e, 0xbf, 0xa0, 0x61, 0x5b, 0x0d, 0x28, 0x84, 0x70, 0x7c, 0xbf,
	0xed, 0x9b, 0xd7, 0x7d, 0xb3, 0xd0, 0x24, 0x4c, 0x17, 0x6a, 0x82, 0xdd, 0x24, 0x35, 0x6c, 0x44,
	0x45, 0xe3, 0x67, 0x46, 0xb2, 0x06, 0x95, 0xa7, 0x38, 0xe1, 0x95, 0xbc, 0x87, 0xf3, 0x57, 0xe4,
	0xa5, 0x49, 0xe7, 0x3e, 0x7e, 0x64, 0x48, 0x2c, 0x3c, 0xa8, 0xe9, 0x9c, 0x78, 0xa5, 0xeb, 0xd2,
	0x5d, 0xc3, 0xff, 0x91, 0xb2, 0x07, 0xad, 0x80, 0xc3, 0x94, 0x7f, 0x0d, 0x94, 0x18, 0x4d, 0x28,
	0x3a, 0xd0, 0xa0, 0x65, 0x98, 0xc6, 0xe3, 0x39, 0xae, 0xbc, 0x13, 0xeb, 0xa9, 0x5b, 0xf0, 0x82,
	0x2b, 0x19, 0x41, 0xab, 0xf8, 0x3e, 0xe0, 0x90, 0x33, 0xf2, 0x31, 0x37, 0xed, 0x8d, 0x11, 0x97,
	0x50, 0xcd, 0x12, 0x56, 0x31, 0xda, 0x59, 0x65, 0xbf, 0x50, 0xe2, 0x0a, 0x60, 0xaa, 0x68, 0x3e,
	0xce, 0x28, 0x8c, 0xd0, 0x2b, 0xdb, 0xb3, 0xc6, 0x9a, 0x8c, 0xd6, 0x40, 0xbe, 0x41, 0xbb, 0x08,
	0x1a, 0xa8, 0x30, 0xd2, 0x86, 0x58, 0x4d, 0x68, 0xf3, 0x1f, 0xb5, 0x99, 0xe2, 0x58, 0xe9, 0x99,
	0xb1, 0x81, 0xae, 0x5f, 0x5f, 0x83, 0x67, 0x3d, 0x33, 0xa2, 0x05, 0x15, 0xe2, 0x90, 0xc9, 0x06,
	0xba, 0x7e, 0x2e, 0x1e, 0xbe, 0xca, 0x50, 0x0b, 0xf2, 0xf2, 0xc4, 0x2d, 0x9c, 0x0e, 0x95, 0x8e,
	0x84, 0xdb, 0xb5, 0xfd, 0x75, 0x6d, 0x79, 0xed, 0x2d, 0x25, 0x1d, 0x31, 0x00, 0x77, 0xb3, 0x20,
	0x71, 0x51, 0x9c, 0x6f, 0x37, 0xdc, 0xee, 0x14, 0x78, 0x57, 0x99, 0xd2, 0x11, 0x7d, 0x68, 0x8e,
	0x92, 0x69, 0xc8, 0x78, 0x60, 0xcc, 0xdf, 0xf4, 0x47, 0x38, 0x0b, 0xd8, 0x24, 0x47, 0xba, 0xfa,
	0xd0, 0xf4, 0x31, 0x36, 0x8b, 0x63, 0xd3, 0x06, 0xe0, 0x6e, 0xec, 0x95, 0x0e, 0xdd, 0x75, 0xd7,
	0x1b, 0x90, 0x8e, 0x18, 0x82, 0xf8, 0xbf, 0xb4, 0x7d, 0xb3, 0x6e, 0xb6, 0xf1, 0x8e, 0x35, 0x4b,
	0xe7, 0xbd, 0x6a, 0xdf, 0x79, 0xef, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x42, 0x97, 0x36, 0xf8,
	0x02, 0x00, 0x00,
}
