// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response/response.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexResponse struct {
	// lensIdentifier is the identifier of the indexed object according to the lens system
	LensIdentifier string `protobuf:"bytes,1,opt,name=lensIdentifier,proto3" json:"lensIdentifier,omitempty"`
	// keywords  are the keywords that you can use to search for this object within lens
	Keywords []string `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
	// data is miscellaneous data associated with the response
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResponse) Reset()         { *m = IndexResponse{} }
func (m *IndexResponse) String() string { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()    {}
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d05759dee52fb5, []int{0}
}

func (m *IndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponse.Unmarshal(m, b)
}
func (m *IndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponse.Marshal(b, m, deterministic)
}
func (m *IndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponse.Merge(m, src)
}
func (m *IndexResponse) XXX_Size() int {
	return xxx_messageInfo_IndexResponse.Size(m)
}
func (m *IndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponse proto.InternalMessageInfo

func (m *IndexResponse) GetLensIdentifier() string {
	if m != nil {
		return m.LensIdentifier
	}
	return ""
}

func (m *IndexResponse) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *IndexResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimpleSearchResponse struct {
	// name is the "name" of the object, such as an IPFS content hash
	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	// objectType is the type of the object, such as IPLD
	ObjectType           string   `protobuf:"bytes,2,opt,name=objectType,proto3" json:"objectType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleSearchResponse) Reset()         { *m = SimpleSearchResponse{} }
func (m *SimpleSearchResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleSearchResponse) ProtoMessage()    {}
func (*SimpleSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d05759dee52fb5, []int{1}
}

func (m *SimpleSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleSearchResponse.Unmarshal(m, b)
}
func (m *SimpleSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleSearchResponse.Marshal(b, m, deterministic)
}
func (m *SimpleSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleSearchResponse.Merge(m, src)
}
func (m *SimpleSearchResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleSearchResponse.Size(m)
}
func (m *SimpleSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleSearchResponse proto.InternalMessageInfo

func (m *SimpleSearchResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *SimpleSearchResponse) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

type AdvancedSearchResponse struct {
	Objects              []*Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AdvancedSearchResponse) Reset()         { *m = AdvancedSearchResponse{} }
func (m *AdvancedSearchResponse) String() string { return proto.CompactTextString(m) }
func (*AdvancedSearchResponse) ProtoMessage()    {}
func (*AdvancedSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d05759dee52fb5, []int{2}
}

func (m *AdvancedSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvancedSearchResponse.Unmarshal(m, b)
}
func (m *AdvancedSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvancedSearchResponse.Marshal(b, m, deterministic)
}
func (m *AdvancedSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvancedSearchResponse.Merge(m, src)
}
func (m *AdvancedSearchResponse) XXX_Size() int {
	return xxx_messageInfo_AdvancedSearchResponse.Size(m)
}
func (m *AdvancedSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvancedSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdvancedSearchResponse proto.InternalMessageInfo

func (m *AdvancedSearchResponse) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

type Object struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MimeType             string   `protobuf:"bytes,2,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_73d05759dee52fb5, []int{3}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *Object) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Object) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*IndexResponse)(nil), "response.IndexResponse")
	proto.RegisterType((*SimpleSearchResponse)(nil), "response.SimpleSearchResponse")
	proto.RegisterType((*AdvancedSearchResponse)(nil), "response.AdvancedSearchResponse")
	proto.RegisterType((*Object)(nil), "response.object")
}

func init() { proto.RegisterFile("response/response.proto", fileDescriptor_73d05759dee52fb5) }

var fileDescriptor_73d05759dee52fb5 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xda, 0x7e, 0xfd, 0xda, 0xe5, 0x47, 0xc8, 0xaa, 0x20, 0xe2, 0x80, 0xaa, 0x1c, 0x20,
	0x70, 0x48, 0x24, 0x78, 0x02, 0x10, 0x97, 0x4a, 0x3d, 0xb9, 0x3d, 0x71, 0x73, 0xec, 0x25, 0x09,
	0x34, 0x76, 0xe4, 0x98, 0x9f, 0xbc, 0x3d, 0xb2, 0xdd, 0x58, 0x55, 0x6f, 0x33, 0xbb, 0xeb, 0xd9,
	0x19, 0x2f, 0x5c, 0x69, 0xec, 0x5a, 0x25, 0x3b, 0xcc, 0x07, 0x90, 0xb5, 0x5a, 0x19, 0x45, 0x66,
	0x03, 0x4f, 0x4a, 0x38, 0x5b, 0x49, 0x81, 0xbf, 0x74, 0x5f, 0x20, 0xb7, 0x70, 0xbe, 0x43, 0xd9,
	0xad, 0x04, 0x4a, 0x53, 0xbf, 0xd7, 0xa8, 0xe3, 0x68, 0x19, 0xa5, 0x73, 0x7a, 0x54, 0x25, 0xd7,
	0x30, 0xfb, 0xc4, 0xfe, 0x47, 0x69, 0xd1, 0xc5, 0xa3, 0xe5, 0x38, 0x9d, 0xd3, 0xc0, 0x09, 0x81,
	0x89, 0x60, 0x86, 0xc5, 0xe3, 0x65, 0x94, 0x9e, 0x52, 0x87, 0x93, 0x35, 0x2c, 0x36, 0x75, 0xd3,
	0xee, 0x70, 0x83, 0x4c, 0xf3, 0x2a, 0xec, 0x5b, 0xc0, 0x3f, 0xc9, 0x1a, 0xec, 0xe2, 0xc8, 0x89,
	0x78, 0x42, 0x6e, 0x00, 0x54, 0xf1, 0x81, 0xdc, 0x6c, 0xfb, 0x16, 0xe3, 0x91, 0x73, 0x70, 0x50,
	0x49, 0x5e, 0xe1, 0xf2, 0x59, 0x7c, 0x33, 0xc9, 0x51, 0x1c, 0xe9, 0x3d, 0xc0, 0x7f, 0x3f, 0xe7,
	0x15, 0x4f, 0x1e, 0x2f, 0xb2, 0x10, 0xde, 0x37, 0xe8, 0x30, 0x90, 0x54, 0x30, 0xf5, 0xd0, 0x3a,
	0xb6, 0x8b, 0xf7, 0x59, 0x1d, 0xb6, 0x09, 0x9b, 0xba, 0xc1, 0x03, 0x07, 0x81, 0xdb, 0x1e, 0x67,
	0x06, 0x4b, 0xa5, 0x7b, 0x97, 0x72, 0x4e, 0x03, 0xb7, 0x5a, 0xc6, 0xbe, 0x99, 0x78, 0x2d, 0x8b,
	0x5f, 0xee, 0xdf, 0xee, 0xca, 0xda, 0x54, 0x5f, 0x45, 0xc6, 0x55, 0x93, 0xd3, 0xad, 0x66, 0x02,
	0xd7, 0x46, 0xe4, 0xa5, 0x6e, 0x79, 0x6e, 0x7f, 0x36, 0x5c, 0xa8, 0x98, 0xba, 0x13, 0x3d, 0xfd,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x58, 0x5b, 0xc9, 0xb7, 0xbd, 0x01, 0x00, 0x00,
}
