// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexReq_Type int32

const (
	IndexReq_UNKNOWN IndexReq_Type = 0
	IndexReq_IPLD    IndexReq_Type = 1
)

var IndexReq_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "IPLD",
}
var IndexReq_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"IPLD":    1,
}

func (x IndexReq_Type) String() string {
	return proto.EnumName(IndexReq_Type_name, int32(x))
}
func (IndexReq_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{0, 0}
}

type IndexReq struct {
	Type                 IndexReq_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=IndexReq_Type" json:"type,omitempty"`
	Hash                 string            `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	DisplayName          string            `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Tags                 []string          `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Options              *IndexReq_Options `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *IndexReq) Reset()         { *m = IndexReq{} }
func (m *IndexReq) String() string { return proto.CompactTextString(m) }
func (*IndexReq) ProtoMessage()    {}
func (*IndexReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{0}
}
func (m *IndexReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexReq.Unmarshal(m, b)
}
func (m *IndexReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexReq.Marshal(b, m, deterministic)
}
func (dst *IndexReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexReq.Merge(dst, src)
}
func (m *IndexReq) XXX_Size() int {
	return xxx_messageInfo_IndexReq.Size(m)
}
func (m *IndexReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexReq.DiscardUnknown(m)
}

var xxx_messageInfo_IndexReq proto.InternalMessageInfo

func (m *IndexReq) GetType() IndexReq_Type {
	if m != nil {
		return m.Type
	}
	return IndexReq_UNKNOWN
}

func (m *IndexReq) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *IndexReq) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *IndexReq) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *IndexReq) GetOptions() *IndexReq_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type IndexReq_Options struct {
	Reindex              bool     `protobuf:"varint,1,opt,name=reindex,proto3" json:"reindex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexReq_Options) Reset()         { *m = IndexReq_Options{} }
func (m *IndexReq_Options) String() string { return proto.CompactTextString(m) }
func (*IndexReq_Options) ProtoMessage()    {}
func (*IndexReq_Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{0, 0}
}
func (m *IndexReq_Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexReq_Options.Unmarshal(m, b)
}
func (m *IndexReq_Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexReq_Options.Marshal(b, m, deterministic)
}
func (dst *IndexReq_Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexReq_Options.Merge(dst, src)
}
func (m *IndexReq_Options) XXX_Size() int {
	return xxx_messageInfo_IndexReq_Options.Size(m)
}
func (m *IndexReq_Options) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexReq_Options.DiscardUnknown(m)
}

var xxx_messageInfo_IndexReq_Options proto.InternalMessageInfo

func (m *IndexReq_Options) GetReindex() bool {
	if m != nil {
		return m.Reindex
	}
	return false
}

type IndexResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResp) Reset()         { *m = IndexResp{} }
func (m *IndexResp) String() string { return proto.CompactTextString(m) }
func (*IndexResp) ProtoMessage()    {}
func (*IndexResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{1}
}
func (m *IndexResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResp.Unmarshal(m, b)
}
func (m *IndexResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResp.Marshal(b, m, deterministic)
}
func (dst *IndexResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResp.Merge(dst, src)
}
func (m *IndexResp) XXX_Size() int {
	return xxx_messageInfo_IndexResp.Size(m)
}
func (m *IndexResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResp.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResp proto.InternalMessageInfo

type SearchReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchReq) Reset()         { *m = SearchReq{} }
func (m *SearchReq) String() string { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()    {}
func (*SearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{2}
}
func (m *SearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReq.Unmarshal(m, b)
}
func (m *SearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReq.Marshal(b, m, deterministic)
}
func (dst *SearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReq.Merge(dst, src)
}
func (m *SearchReq) XXX_Size() int {
	return xxx_messageInfo_SearchReq.Size(m)
}
func (m *SearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReq proto.InternalMessageInfo

type SearchResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResp) Reset()         { *m = SearchResp{} }
func (m *SearchResp) String() string { return proto.CompactTextString(m) }
func (*SearchResp) ProtoMessage()    {}
func (*SearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{3}
}
func (m *SearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResp.Unmarshal(m, b)
}
func (m *SearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResp.Marshal(b, m, deterministic)
}
func (dst *SearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResp.Merge(dst, src)
}
func (m *SearchResp) XXX_Size() int {
	return xxx_messageInfo_SearchResp.Size(m)
}
func (m *SearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResp proto.InternalMessageInfo

type RemoveReq struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReq) Reset()         { *m = RemoveReq{} }
func (m *RemoveReq) String() string { return proto.CompactTextString(m) }
func (*RemoveReq) ProtoMessage()    {}
func (*RemoveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{4}
}
func (m *RemoveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReq.Unmarshal(m, b)
}
func (m *RemoveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReq.Marshal(b, m, deterministic)
}
func (dst *RemoveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReq.Merge(dst, src)
}
func (m *RemoveReq) XXX_Size() int {
	return xxx_messageInfo_RemoveReq.Size(m)
}
func (m *RemoveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReq proto.InternalMessageInfo

func (m *RemoveReq) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RemoveResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResp) Reset()         { *m = RemoveResp{} }
func (m *RemoveResp) String() string { return proto.CompactTextString(m) }
func (*RemoveResp) ProtoMessage()    {}
func (*RemoveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_187981c3aceb4f84, []int{5}
}
func (m *RemoveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResp.Unmarshal(m, b)
}
func (m *RemoveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResp.Marshal(b, m, deterministic)
}
func (dst *RemoveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResp.Merge(dst, src)
}
func (m *RemoveResp) XXX_Size() int {
	return xxx_messageInfo_RemoveResp.Size(m)
}
func (m *RemoveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IndexReq)(nil), "IndexReq")
	proto.RegisterType((*IndexReq_Options)(nil), "IndexReq.Options")
	proto.RegisterType((*IndexResp)(nil), "IndexResp")
	proto.RegisterType((*SearchReq)(nil), "SearchReq")
	proto.RegisterType((*SearchResp)(nil), "SearchResp")
	proto.RegisterType((*RemoveReq)(nil), "RemoveReq")
	proto.RegisterType((*RemoveResp)(nil), "RemoveResp")
	proto.RegisterEnum("IndexReq_Type", IndexReq_Type_name, IndexReq_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LensV2Client is the client API for LensV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LensV2Client interface {
	Index(ctx context.Context, in *IndexReq, opts ...grpc.CallOption) (*IndexResp, error)
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveResp, error)
}

type lensV2Client struct {
	cc *grpc.ClientConn
}

func NewLensV2Client(cc *grpc.ClientConn) LensV2Client {
	return &lensV2Client{cc}
}

func (c *lensV2Client) Index(ctx context.Context, in *IndexReq, opts ...grpc.CallOption) (*IndexResp, error) {
	out := new(IndexResp)
	err := c.cc.Invoke(ctx, "/LensV2/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lensV2Client) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, "/LensV2/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lensV2Client) Remove(ctx context.Context, in *RemoveReq, opts ...grpc.CallOption) (*RemoveResp, error) {
	out := new(RemoveResp)
	err := c.cc.Invoke(ctx, "/LensV2/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LensV2Server is the server API for LensV2 service.
type LensV2Server interface {
	Index(context.Context, *IndexReq) (*IndexResp, error)
	Search(context.Context, *SearchReq) (*SearchResp, error)
	Remove(context.Context, *RemoveReq) (*RemoveResp, error)
}

func RegisterLensV2Server(s *grpc.Server, srv LensV2Server) {
	s.RegisterService(&_LensV2_serviceDesc, srv)
}

func _LensV2_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensV2Server).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LensV2/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensV2Server).Index(ctx, req.(*IndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LensV2_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensV2Server).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LensV2/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensV2Server).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LensV2_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensV2Server).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LensV2/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensV2Server).Remove(ctx, req.(*RemoveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LensV2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LensV2",
	HandlerType: (*LensV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _LensV2_Index_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _LensV2_Search_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _LensV2_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_187981c3aceb4f84) }

var fileDescriptor_service_187981c3aceb4f84 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x59, 0x29, 0x94, 0x4e, 0x91, 0xe0, 0x9c, 0x9a, 0x26, 0xc6, 0xba, 0x5c, 0x48, 0x4c,
	0xf6, 0x50, 0x5f, 0xc1, 0x0b, 0x91, 0x14, 0xb3, 0xfe, 0x3b, 0x9a, 0x0a, 0x13, 0x69, 0x22, 0xed,
	0xd2, 0x6d, 0x88, 0xbc, 0xb2, 0x4f, 0x61, 0x76, 0x61, 0x5b, 0x6f, 0x33, 0xf3, 0x7d, 0xd3, 0xdf,
	0x7c, 0x5d, 0xb8, 0xd4, 0x54, 0x1f, 0x8a, 0x35, 0x09, 0x55, 0x57, 0x4d, 0xc5, 0x7f, 0x19, 0x8c,
	0x16, 0xe5, 0x86, 0x7e, 0x24, 0xed, 0x91, 0x83, 0xd7, 0x1c, 0x15, 0x45, 0x2c, 0x61, 0xf3, 0x49,
	0x3a, 0x11, 0x4e, 0x10, 0x2f, 0x47, 0x45, 0xd2, 0x6a, 0x88, 0xe0, 0x6d, 0x73, 0xbd, 0x8d, 0x2e,
	0x12, 0x36, 0x0f, 0xa4, 0xad, 0xf1, 0x16, 0xc6, 0x9b, 0x42, 0xab, 0xef, 0xfc, 0xf8, 0x51, 0xe6,
	0x3b, 0x8a, 0xfa, 0x56, 0x0b, 0xcf, 0xb3, 0x2c, 0xdf, 0xd9, 0xb5, 0x26, 0xff, 0xd2, 0x91, 0x97,
	0xf4, 0xcd, 0x9a, 0xa9, 0xf1, 0x0e, 0xfc, 0x4a, 0x35, 0x45, 0x55, 0xea, 0x68, 0x90, 0xb0, 0x79,
	0x98, 0x5e, 0x75, 0xc4, 0xd5, 0x49, 0x90, 0xce, 0x11, 0xcf, 0xc0, 0x3f, 0xcf, 0x30, 0x02, 0xbf,
	0xa6, 0xc2, 0x38, 0xed, 0xa5, 0x23, 0xe9, 0x5a, 0x7e, 0x0d, 0x9e, 0x39, 0x15, 0x43, 0xf0, 0x5f,
	0xb3, 0xc7, 0x6c, 0xf5, 0x9e, 0x4d, 0x7b, 0x38, 0x02, 0x6f, 0xf1, 0xb4, 0x7c, 0x98, 0x32, 0x1e,
	0x42, 0x70, 0x06, 0x68, 0x65, 0x9a, 0x67, 0xca, 0xeb, 0xf5, 0x56, 0xd2, 0x9e, 0x8f, 0x01, 0x5c,
	0xa3, 0x15, 0xbf, 0x81, 0x40, 0xd2, 0xae, 0x3a, 0x90, 0xf9, 0x29, 0x2e, 0x30, 0xeb, 0x02, 0x1b,
	0xbb, 0x33, 0x68, 0x95, 0x36, 0x30, 0x5c, 0x52, 0xa9, 0xdf, 0x52, 0x4c, 0x60, 0x60, 0x01, 0x18,
	0xb4, 0x49, 0x62, 0x10, 0x1d, 0xb3, 0x87, 0x33, 0x18, 0x9e, 0x40, 0x08, 0xa2, 0xc5, 0xc7, 0xa1,
	0xf8, 0x47, 0xb7, 0xa6, 0xd3, 0xe7, 0x11, 0x44, 0x7b, 0x48, 0x1c, 0x8a, 0x8e, 0xc9, 0x7b, 0x9f,
	0x43, 0xfb, 0x80, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x28, 0xbf, 0x3f, 0xd1, 0x01,
	0x00, 0x00,
}
