// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignResponse struct {
	H                    string   `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
	R                    string   `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	S                    string   `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	V                    string   `protobuf:"bytes,4,opt,name=v,proto3" json:"v,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Hash                 string   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Sig                  string   `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{0}
}

func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (m *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(m, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetH() string {
	if m != nil {
		return m.H
	}
	return ""
}

func (m *SignResponse) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *SignResponse) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *SignResponse) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *SignResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SignResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SignResponse) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func init() {
	proto.RegisterType((*SignResponse)(nil), "response.SignResponse")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_0fbc901015fa5021) }

var fileDescriptor_0fbc901015fa5021 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcf, 0xb1, 0xaa, 0xc2, 0x30,
	0x14, 0xc6, 0x71, 0x72, 0xdb, 0xdb, 0xde, 0x1b, 0x8a, 0x48, 0xa6, 0x33, 0x8a, 0x93, 0x22, 0x34,
	0xa0, 0x6f, 0xe0, 0xec, 0x54, 0x9d, 0xdc, 0xd2, 0x26, 0x24, 0x1d, 0x6c, 0xc2, 0x39, 0xb5, 0xe0,
	0x0b, 0xf8, 0xdc, 0x92, 0xd4, 0x6e, 0xdf, 0xef, 0x3f, 0x9d, 0xc3, 0x57, 0x68, 0x28, 0xf8, 0x81,
	0x4c, 0x1d, 0xd0, 0x8f, 0x5e, 0xfc, 0x2d, 0xde, 0xbe, 0x19, 0xaf, 0xae, 0xbd, 0x1d, 0x9a, 0x6f,
	0x10, 0x15, 0x67, 0x0e, 0xd8, 0x86, 0xed, 0xfe, 0x1b, 0xe6, 0xa2, 0x10, 0x7e, 0x66, 0x61, 0x14,
	0x41, 0x36, 0x8b, 0xa2, 0x26, 0xc8, 0x67, 0x4d, 0x02, 0x78, 0xa9, 0xb4, 0x46, 0x43, 0x04, 0xbf,
	0xa9, 0x2d, 0x14, 0x82, 0xe7, 0x4e, 0x91, 0x83, 0x22, 0xe5, 0xb4, 0xc5, 0x9a, 0x67, 0xd4, 0x5b,
	0x28, 0x53, 0x8a, 0xf3, 0x7c, 0xb8, 0xef, 0x6d, 0x3f, 0xba, 0x67, 0x5b, 0x77, 0xfe, 0x21, 0x9b,
	0x1b, 0x2a, 0x6d, 0x2e, 0xa3, 0x96, 0x16, 0x43, 0x27, 0xa7, 0xa3, 0x0c, 0xea, 0x25, 0x97, 0xab,
	0xdb, 0x22, 0xbd, 0x71, 0xfa, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x3a, 0x53, 0x99, 0xd8, 0x00,
	0x00, 0x00,
}
