// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Index struct {
	// type is the "type" of data, such as IPLD
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// identifier is the identifier of the object, such as an IPFS content hash
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// reindex indicates whether the object should be indexed again
	Reindex              bool     `protobuf:"varint,3,opt,name=reindex,proto3" json:"reindex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Index) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Index) GetReindex() bool {
	if m != nil {
		return m.Reindex
	}
	return false
}

type Search struct {
	// keywords to search by
	Keywords []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	// options are used to configure the query
	Options              *Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

func (m *Search) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *Search) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type Options struct {
	Categories           []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*Index)(nil), "request.Index")
	proto.RegisterType((*Search)(nil), "request.Search")
	proto.RegisterType((*Options)(nil), "request.Options")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0xab, 0xdb, 0xdd, 0x11, 0x41, 0x72, 0x0a, 0x1e, 0xa4, 0xf4, 0xd4, 0x55, 0x68,
	0x60, 0xfd, 0x07, 0xde, 0x04, 0x41, 0x89, 0x7a, 0xf1, 0xd6, 0x6d, 0xc6, 0x6e, 0x50, 0x9b, 0x38,
	0x99, 0x55, 0xf7, 0xdf, 0x4b, 0x62, 0xbb, 0xf4, 0x96, 0xf7, 0x65, 0xde, 0x9b, 0xc7, 0xc0, 0x19,
	0xe1, 0xd7, 0x0e, 0x03, 0xd7, 0x9e, 0x1c, 0x3b, 0x91, 0x0f, 0xb2, 0x7c, 0x81, 0x93, 0xbb, 0xde,
	0xe0, 0xaf, 0x10, 0x70, 0xcc, 0x7b, 0x8f, 0x32, 0x2b, 0xb2, 0x6a, 0xa9, 0xd3, 0x5b, 0x5c, 0x02,
	0x58, 0x83, 0x3d, 0xdb, 0x37, 0x8b, 0x24, 0x8f, 0xd2, 0xcf, 0x84, 0x08, 0x09, 0x39, 0xa1, 0x8d,
	0x76, 0x39, 0x2b, 0xb2, 0x6a, 0xa1, 0x47, 0x59, 0x3e, 0xc2, 0xfc, 0x09, 0x1b, 0x6a, 0xb7, 0xe2,
	0x02, 0x16, 0xef, 0xb8, 0xff, 0x71, 0x64, 0x82, 0xcc, 0x8a, 0x59, 0xb5, 0xd4, 0x07, 0x2d, 0xae,
	0x20, 0x77, 0x9e, 0xad, 0xeb, 0x43, 0x0a, 0x3f, 0x5d, 0x9f, 0xd7, 0x63, 0xcd, 0x87, 0x7f, 0xae,
	0xc7, 0x81, 0x72, 0x05, 0xf9, 0xc0, 0x62, 0xad, 0xb6, 0x61, 0xec, 0x1c, 0x59, 0x8c, 0xce, 0x18,
	0x3a, 0x21, 0xb7, 0xd7, 0xaf, 0xab, 0xce, 0xf2, 0x76, 0xb7, 0xa9, 0x5b, 0xf7, 0xa9, 0xf4, 0x33,
	0x35, 0x06, 0xef, 0xd9, 0xa8, 0x8e, 0x7c, 0xab, 0xbe, 0xd7, 0xea, 0x03, 0xfb, 0xa0, 0x86, 0x45,
	0x9b, 0x79, 0x3a, 0xc8, 0xcd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x85, 0x4c, 0x32, 0x21,
	0x01, 0x00, 0x00,
}
