// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request/request.proto

package request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexRequest struct {
	// dataType is the "type" of data, such as IPLD
	DataType string `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	// objectIdentifier is the identifier of the object, such as an IPFS content hash
	ObjectIdentifier     string   `protobuf:"bytes,2,opt,name=objectIdentifier,proto3" json:"objectIdentifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexRequest) Reset()         { *m = IndexRequest{} }
func (m *IndexRequest) String() string { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()    {}
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d73066fed3fbb2, []int{0}
}

func (m *IndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexRequest.Unmarshal(m, b)
}
func (m *IndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexRequest.Marshal(b, m, deterministic)
}
func (m *IndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexRequest.Merge(m, src)
}
func (m *IndexRequest) XXX_Size() int {
	return xxx_messageInfo_IndexRequest.Size(m)
}
func (m *IndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexRequest proto.InternalMessageInfo

func (m *IndexRequest) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *IndexRequest) GetObjectIdentifier() string {
	if m != nil {
		return m.ObjectIdentifier
	}
	return ""
}

type SearchRequest struct {
	// repeated means there can be 0 or more "keywords"
	Keywords             []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_30d73066fed3fbb2, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func init() {
	proto.RegisterType((*IndexRequest)(nil), "request.IndexRequest")
	proto.RegisterType((*SearchRequest)(nil), "request.SearchRequest")
}

func init() { proto.RegisterFile("request/request.proto", fileDescriptor_30d73066fed3fbb2) }

var fileDescriptor_30d73066fed3fbb2 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x52, 0x18, 0x17, 0x8f, 0x67, 0x5e, 0x4a, 0x6a, 0x45, 0x10, 0x84, 0x2f, 0x24, 0xc5, 0xc5, 0x91,
	0x92, 0x58, 0x92, 0x18, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7,
	0x0b, 0x69, 0x71, 0x09, 0xe4, 0x27, 0x65, 0xa5, 0x26, 0x97, 0x78, 0xa6, 0xa4, 0xe6, 0x95, 0x64,
	0xa6, 0x65, 0xa6, 0x16, 0x49, 0x30, 0x81, 0xd5, 0x60, 0x88, 0x2b, 0x69, 0x73, 0xf1, 0x06, 0xa7,
	0x26, 0x16, 0x25, 0x67, 0x20, 0x19, 0x9c, 0x9d, 0x5a, 0x59, 0x9e, 0x5f, 0x94, 0x52, 0x2c, 0xc1,
	0xa8, 0xc0, 0x0c, 0x32, 0x18, 0xc6, 0x77, 0xd2, 0x88, 0x52, 0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d,
	0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x0f, 0x0a, 0x29, 0x4a, 0x4c, 0x49, 0xf5, 0x29, 0x49, 0xd1, 0x4f,
	0x2f, 0x2a, 0x48, 0xd6, 0xcf, 0x49, 0xcd, 0x2b, 0x86, 0xb9, 0x3e, 0x89, 0x0d, 0xec, 0x7c, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0xce, 0xeb, 0x63, 0xd7, 0x00, 0x00, 0x00,
}
